CREATE DATABASE IF NOT EXISTS online_drink_shop CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE online_drink_shop;
CREATE TABLE users(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,email VARCHAR(150) NOT NULL UNIQUE,password VARCHAR(255) NOT NULL,role ENUM('customer','admin') DEFAULT 'customer',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE categories(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(80) NOT NULL UNIQUE);
CREATE TABLE drinks(id INT AUTO_INCREMENT PRIMARY KEY,category_id INT NULL,name VARCHAR(120) NOT NULL,description VARCHAR(255),price DECIMAL(10,2) NOT NULL,stock INT NOT NULL DEFAULT 0,image VARCHAR(255) DEFAULT NULL,is_active TINYINT(1) DEFAULT 1,FOREIGN KEY(category_id) REFERENCES categories(id) ON DELETE SET NULL);
CREATE TABLE orders(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NULL,customer_name VARCHAR(100) NOT NULL,phone VARCHAR(30) NOT NULL,address VARCHAR(255),fulfillment ENUM('delivery','pickup') DEFAULT 'delivery',total DECIMAL(10,2) NOT NULL,status ENUM('Pending','Confirmed','Preparing','Ready','Out for Delivery','Delivered','Picked Up','Cancelled') DEFAULT 'Pending',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE order_items(id INT AUTO_INCREMENT PRIMARY KEY,order_id INT NOT NULL,drink_id INT NULL,drink_name VARCHAR(120) NOT NULL,price DECIMAL(10,2) NOT NULL,qty INT NOT NULL,size VARCHAR(30),sugar VARCHAR(30),ice VARCHAR(30),FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,FOREIGN KEY(drink_id) REFERENCES drinks(id) ON DELETE SET NULL);
CREATE TABLE payments(id INT AUTO_INCREMENT PRIMARY KEY,order_id INT NOT NULL,method VARCHAR(50) NOT NULL,status ENUM('Pending','Authorized','Paid','Failed') DEFAULT 'Paid',amount DECIMAL(10,2) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE);
CREATE TABLE feedback(id INT AUTO_INCREMENT PRIMARY KEY,order_id INT NULL,user_id INT NULL,rating TINYINT,message TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE SET NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL);
INSERT INTO categories(name) VALUES ('Milk Tea'),('Coffee'),('Fruit Tea'),('Smoothie');
INSERT INTO drinks(category_id,name,description,price,stock) VALUES
(1,'Classic Milk Tea','Creamy tea with fresh milk',2.50,30),(1,'Brown Sugar Milk Tea','Milk tea with brown sugar flavor',3.00,25),(2,'Iced Coffee','Strong coffee served cold',2.00,35),(2,'Iced Latte','Espresso with milk',2.75,20),(3,'Passion Fruit Tea','Fresh and fruity tea',2.50,24),(3,'Lemon Tea','Refreshing lemon tea',2.00,28),(4,'Mango Smoothie','Creamy mango smoothie',3.25,18),(4,'Strawberry Smoothie','Fresh strawberry smoothie',3.25,18);
